config/routes.rb
Onedoc::Application.routes.draw do
  get "dcrelations/create"

  get "dcrelations/destroy"

  resources :doctors
  resources :clinics 
  resources :dcrelations

  root to: 'onedoc#home'

  match 'create' => 'dcrelations#create', :as => :create
  match 'destroy' => 'dcrelations#destroy'

  match '/add', to: 'doctors#new'
  match '/create', to: 'doctor#create'
  match '/update', to: 'doctors#update'
  match '/delete', to: 'doctors#destroy'

  match '/add', to: 'clinics#new'
  match '/create', to: 'clinic#create'
  match '/update', to: 'clinics#update'
  match '/delete', to: 'clinics#destroy'

  get "doctor/create"

  get "doctor/update"

  get "doctor/delete"

  get "clinic/create"

  get "clinic/update"

  get "clinic/delete"

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  attr_accessible :clinic_id, :name
  has_many :dcrelations, dependent: :destroy
  has_many :doctors, :through => :dcrelations
end

app/models/dcrelation.rb
class Dcrelation < ActiveRecord::Base
  attr_accessible :clinic_id, :doctor_id
  belongs_to :doctor
  belongs_to :clinic
  validates :clinic_id, :doctor_id, presence: true
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  attr_accessible :doctor_id, :name
  has_one :dcrelation,  dependent: :destroy
  has_one :clinic, :through => :dcrelation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clinics }
    end
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
    @clinic = Clinic.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clinic }
    end
  end

  # GET /clinics/new
  # GET /clinics/new.json
  def new
    @clinic = Clinic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clinic }
    end
  end

  # GET /clinics/1/edit
  def edit
    @clinic = Clinic.find(params[:id])
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(params[:clinic])

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clinic was successfully created.' }
        format.json { render json: @clinic, status: :created, location: @clinic }
      else
        format.html { render action: "new" }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clinics/1
  # PUT /clinics/1.json
  def update
    @clinic = Clinic.find(params[:id])

    respond_to do |format|
      if @clinic.update_attributes(params[:clinic])
        format.html { redirect_to @clinic, notice: 'Clinic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic = Clinic.find(params[:id])
    @clinic.destroy

    respond_to do |format|
      format.html { redirect_to clinics_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/dcrelations_controller.rb
class DcrelationsController < ApplicationController
  def create
    @dcrelation = Dcrelation.new(:clinic_id => params[:clinic_id],:doctor_id => params[:doctor_id])
    if @dcrelation.save
      flash[:success] = "doctor added!"
      redirect_to :back
    else
      render :back
    end
  end

  def destroy
    @dcrelation = Dcrelation.find(params[:id])
    @dcrelation.destroy
    redirect_to :back
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @doctors }
    end
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/new
  # GET /doctors/new.json
  def new
    @doctor = Doctor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/1/edit
  def edit
    @doctor = Doctor.find(params[:id])
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(params[:doctor])

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render json: @doctor, status: :created, location: @doctor }
      else
        format.html { render action: "new" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /doctors/1
  # PUT /doctors/1.json
  def update
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      if @doctor.update_attributes(params[:doctor])
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end

  #def addclinic
  #  @rel = Dcrelation.find(params[:id])
  #  @c = Clinic.find(@rel.cid)
  #end


end

app/controllers/onedoc_controller.rb
class OnedocController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/dcrelations_helper.rb
module DcrelationsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/onedoc_helper.rb
module OnedocHelper
end

app/views/clinics/_form.html.erb
<%= form_for(@clinic) do |f| %>
  <% if @clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinic.errors.count, "error") %> prohibited this clinic from being saved:</h2>

      <ul>
      <% @clinic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :clinic_id %><br />
    <%= f.number_field :clinic_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clinics/edit.html.erb
<h1>Editing clinic</h1>

<%= render 'form' %>

<%= link_to 'Show', @clinic %> |
<%= link_to 'Back', clinics_path %>

app/views/clinics/index.html.erb
<h1>Listing clinics</h1>

<table border="1">
  <tr>
    <th>Clinic Name</th>
    <th>Clinic Id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% if @clinics.present? %>
<% @clinics.each do |clinic| %>
  <tr>
    <td><%= clinic.name %></td>
    <td><%= clinic.clinic_id %></td>
    <td><%= link_to 'More', clinic %></td>
    <td><%= link_to 'Update', edit_clinic_path(clinic) %></td>
    <td><%= link_to 'Destroy', clinic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<% end %>
</table>
<br />
<%= link_to 'back to main', root_url %>
<br />
<%= link_to 'New Clinic', new_clinic_path %>

app/views/clinics/new.html.erb
<h1>New clinic</h1>

<%= render 'form' %>

<%= link_to 'Back', clinics_path %>

app/views/clinics/show.html.erb
<p id="notice"><%= notice %></p>

<p><h1>
  <b>Clinic Name:</b>
  <%= @clinic.name %>
   </h1>
</p>

<p>
   <h1>
  <b>Clinic Id:</b>
  <%= @clinic.clinic_id %>
   </h1>
</p>
<p><b>Associated Doctors: (<%= @clinic.dcrelations.count %>)</b><p>
    <% if @clinic.dcrelations.any? %>
       <table border="1">
		<tr><td>Doctor Name</td><td>Doctor Id</td></tr>
		<%= @clinic.dcrelations.each do |d| %>	
			<tr><td><%= Doctor.find(d.doctor_id).name %></td><td><%= d.doctor_id %></td>

		    <td><%= link_to 'Destroy', d, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			
		<% end %>
       </table>
    <% end %>
    <p>
      <b>Add more doctors</b>
	<%= render 'shared/dcrelation_form' %>
  </p>
<%= link_to 'Edit', edit_clinic_path(@clinic) %>
<%= link_to 'Back', clinics_path %>

app/views/dcrelations/create.html.erb
<h1>Dcrelations#create</h1>
<p>Find me in app/views/dcrelations/create.html.erb</p>

app/views/dcrelations/destroy.html.erb
<h1>Dcrelations#destroy</h1>
<p>Find me in app/views/dcrelations/destroy.html.erb</p>

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :doctorid %><br />
    <%= f.number_field :doctor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<h1>Listing doctors</h1>

<table border="1">
  <tr>
    <th>Doctor Name</th>
    <th>Doctor Id</th>
    <th></th>
    <th></th>
  </tr>
<% if @doctors.present? %>
<% @doctors.each do |doctor| %>
  <tr>
    <td><%= doctor.name %></td>
    <td><%= doctor.doctor_id %></td>
    <td><%= link_to 'More', doctor %></td>
    <td><%= link_to 'Update', edit_doctor_path(doctor) %></td>
    <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

<%= link_to 'back to main', root_url %>
<br />

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p><h1>
  <b>Doctor Name:</b>
  <%= @doctor.name %></h1>
</p>

<p>
  <h1><b>Doctor Id:</b>
  <%= @doctor.doctor_id %></h1>
</p>

<p><h3><b>Associated Clinics:</b><br/>


	<% if @doctor.dcrelation.present? %>
<table border="1">
<tr>
<td>Clinic name</td><td>Clinic Id</td>
</tr>
<td><%= Clinic.find(@doctor.dcrelation.clinic_id).name %></td><td><%= @doctor.dcrelation.clinic_id %></td>
</h3>
</table>
</p>
	<% end %>


<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onedoc</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/onedoc/home.html.erb
<h1>Welcome to the Onedoc home</h1>
<a href="clinics#index" class="btn btn-primary btn-large">Clinic List</a>
<a href="doctors#index" class="btn btn-primary btn-large">Doctor List</a>

app/views/shared/_dcrelation_form.html.erb
<%= form_tag(:controller => "dcrelations", :method => "post") do %>
  <div class="field">
    <%= hidden_field_tag(:clinic_id, @clinic.clinic_id) %>
    <%= label_tag(:doctor_id, "doctor_id: ") %><br />
    <%= number_field_tag(:doctor_id) %>
  </div>
  <%= submit_tag("Add Doctor") %>
<% end %>